### ISSUE TITLE
`tmp.csd` files in the working directory

### ISSUE THREAD

**Issue by georgefst** [spell-music/csound-expression#70]
Is there any particular reason these are written to the current directory, rather than to `tmp`, or providing an option to specify a location? The average user of `csound-expression` will never want to look at them - it's below the level of abstraction the library works at.

This isn't a huge issue. The only real downside to the status quo seems to be that I always have to add `tmp.csd` to my `.gitignore`.

**Comment by anton-k** [comment]
I see what you mean. I've never bothered with that. 
It was somewhere on background to make it in more consistent way. 

I don't like the tmp solution because it excludes Windows. Maybe we can put it to hidden file under user home directory?
Need to check up the solution for creating hidden files in cross-platform way.

**Comment by anton-k** [comment]
It's not hard to do. Only we need to create cross-platform solution.

**Comment by georgefst** [comment]
> I don't like the tmp solution because it excludes Windows.

[`getTemporaryDirectory`](https://hackage.haskell.org/package/directory-1.3.7.0/docs/System-Directory.html#v:getTemporaryDirectory)?

**Comment by anton-k** [comment]
Ok that's convenient! Thanks for the link. I'll try to do smth about it.
